### ISSUE TITLE
远程主机强迫关闭了一个现有的连接

### ISSUE THREAD

**Issue by ven-leon** [Shih-yenh-suan/javdb-artist-scrape#1]
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
你好，请问这怎么解决？

**Comment by Shih-yenh-suan** [comment]
被网站发现反爬了。接下来我会在代码中加入一个检测函数，当出现ConnectionError后，暂停几秒钟，重新执行request

**Comment by ven-leon** [comment]
好的

**Comment by Shih-yenh-suan** [comment]
#3
